### PR TITLE
Functionaljava

### PR DESCRIPTION
**Pull request by johnmcclean-aol**
Converters for
* JDK
* Guava
* jooλ
* simple-react

Supported Functional Java Monads include

* IO
* Either
* Option
* Stream
* List
* State
* Reader
* Writer
* Trampoline
* Validation

### CODE REVIEW

**Comment by mperry** [comment]
What is the best way for me to get started having a try of this?

**Comment by johnmcclean-aol** [comment]
@mperry  Hey Mark, a couple of options

1. You could try checking out the code on the functionaljava branch and adding some unit tests. I think your main challenge there would be the use of Lombok in the code base. You'd need to install Lombok 1.16.4 into your IDE. Lombok val is used in some places which requires IntelliJ 14.1 and above. Should be no problems with Eclipse. To use AnyM, you only need cyclops-base, to use for comprehensions cyclops-for-comprehensions is also required.
2. I could create a snapshot and make it available somewhere (Maven, or in the releases section as a fatjar?)

**Comment by johnmcclean-aol** [comment]
@mperry Hope your finger is ok, btw. I've added in a conversion of this Scala based blog post to Java8. [Reader Monad for Dependency Injection](http://blog.originate.com/blog/2013/10/21/reader-monad-for-dependency-injection/). There are also some thoughts on how to improve things going forward.

https://github.com/aol/cyclops/blob/functionaljava/cyclops-functionaljava/src/test/java/com/aol/cyclops/functionaljava/reader/DITest.java

**Comment by mperry** [comment]
I will have to look later.  I tried to compile but got an error, see #47.  Yes, the reader monad is a normal function and we use partial application.  Not sure if FJ has a good demo of this in the code.

Tony Morris did a great talk online about this:
- http://chariotsolutions.com/presentation/dependency-injection-without-the-gymnastics/
- https://vimeo.com/44502327

**Comment by johnmcclean-aol** [comment]
Didn't realize the λ caused problems on Windows. We've removed it from some other places. Will remove it entirely.

**Comment by mperry** [comment]
The promise of Java: compile once, debug everywhere.

**Comment by johnmcclean-aol** [comment]
The dreaded lambda character has been removed from the functionaljava branch. Will have to wait until this is merged back to master to remove it fully from there.

**Comment by johnmcclean-aol** [comment]
@mperry  I'm going to merge this into master, I don't doubt we'll have to change some things to get the behaviour correct - but it's probably simpler to do that on a branch with less changes - this one is very large.

**Comment by johnmcclean-aol** [comment]
Feel free to reopen for comments, or continue to comment here / log an issue / email / twitter etc by the way. Just felt this PR was too big.

**Comment by mperry** [comment]
Sure, no problem.

**Pull request merged**
